WSCinemaNaw/Models/Country.cs
namespace WSCinemaNaw.Models
{
    public class Country
    {
        public int CountryID { get; set; }
        public string Name { get; set; }
        public List<Movie>? Movies { get; set; }
    }
}

WSCinemaNaw/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using WSCinemaNaw.Models;
using WSCinemaNaw.Repositories.IRepository;

namespace WSCinemaNaw.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryRepository _countryRepository;

        public CountryController(ICountryRepository countryRepository)
        {
            _countryRepository = countryRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _countryRepository.GetAllAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _countryRepository.GetByIdAsync(id.Value);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Country country)
        {
            if (ModelState.IsValid)
            {
                await _countryRepository.AddAsync(country);
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _countryRepository.GetByIdAsync(id.Value);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Country country)
        {
            if (id != country.CountryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _countryRepository.UpdateAsync(country);
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var country = await _countryRepository.GetByIdAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _countryRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WSCinemaNaw/Views/Country/Create.cshtml
@model WSCinemaNaw.Models.Country

<h2>Create New Country</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WSCinemaNaw/Views/Country/Delete.cshtml
@model WSCinemaNaw.Models.Country

<h2>Delete Country</h2>

<h3>Are you sure you want to delete this?</h3>
<form method="post" action="@Url.Action("DeleteConfirmed", "Country", new { id = Model.CountryID })">
    <input type="hidden" name="Id" value="@Model.CountryID" />
    <div class="form-group">
        <label for="name">Tên danh mục:</label>
        <input type="text" id="name" name="Name" value="@Model.Name" class="form-control" readonly />
    </div>
    <button type="submit" class="btn btn-danger">Xóa</button>
    <a asp-action="Index" asp-route-id="@Model.CountryID" class="btn btn-primary">Back</a>
</form>

WSCinemaNaw/Views/Country/Edit.cshtml
@model WSCinemaNaw.Models.Country

<h2>Edit Country</h2>

<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="CountryID" class="control-label"></label>
        <input asp-for="CountryID" class="form-control" readonly />
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WSCinemaNaw/Views/Country/Index.cshtml
@model IEnumerable<WSCinemaNaw.Models.Country>
<h2>Country</h2>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var country in Model)
        {
            <tr>
                <td>@country.CountryID</td>
                <td>@country.Name</td>
                <td>
                    <a asp-action="Delete" asp-route-id="@country.CountryID">Delete</a> |
                    <a asp-action="Edit" asp-route-id="@country.CountryID">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Create">Thêm danh mục mới</a>