WSCinemaNaw/Models/Showtime.cs
namespace WSCinemaNaw.Models
{
    public class Showtime
    {
        public int ShowtimeID { get; set; }
        public int MovieID { get; set; }
        public int TheaterID { get; set; }
        public int RoomID { get; set; }
        public DateTime ShowtimeDate { get; set; }
        public Movie? Movie { get; set; }
        public Room? Room { get; set; }
        public Theater? Theater { get; set; }
        public List<SeatBooking>? SeatBookings { get; set; }
    }
}

WSCinemaNaw/Controllers/ShowtimeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;
using WSCinemaNaw.Data;
using WSCinemaNaw.Models;
using WSCinemaNaw.Repositories.IRepository;
using WSCinemaNaw.Repository.IRepository;

namespace WSCinemaNaw.Controllers
{
    public class ShowtimeController : Controller
    {
        private readonly IShowtimeRepository _showtimeRepository;
        private readonly IMovieRepository _movieRepository;
        private readonly ITheaterRepository _theaterRepository;
        private readonly IRoomRepository _roomRepository;
        private readonly ApplicationDbContext _context;

        public ShowtimeController(IShowtimeRepository showtimeRepository, IMovieRepository movieRepository, ITheaterRepository heaterRepository, IRoomRepository roomRepository, ApplicationDbContext context)
        {
            _showtimeRepository = showtimeRepository;
            _theaterRepository = heaterRepository;
            _roomRepository = roomRepository;
            _movieRepository = movieRepository;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var showtime = await _showtimeRepository.GetAllWithTheatersAsync();
            return View(showtime);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showtime = await _showtimeRepository.GetByIdAsync(id.Value);
            if (showtime == null)
            {
                return NotFound();
            }

            ViewBag.Movies = new SelectList(await _movieRepository.GetAllAsync(), "MovieID", "Title");
            ViewBag.Rooms = new SelectList(await _roomRepository.GetAllAsync(), "RoomID", "Name");
            ViewBag.Theaters = new SelectList(await _theaterRepository.GetAllAsync(), "TheaterID", "Name");
            return View(showtime);
        }

        public async Task<IActionResult> Create()
        {

            ViewBag.Movies = new SelectList(await _movieRepository.GetAllAsync(), "MovieID", "Title");
            ViewBag.Rooms = new SelectList(await _roomRepository.GetAllAsync(), "RoomID", "Name");
            ViewBag.Theaters = new SelectList(await _theaterRepository.GetAllAsync(), "TheaterID", "Name");
            return View();
        }

        private async Task SaveShowtime(Showtime showtime, string releaseDate)
        {
            showtime.ShowtimeDate = ConvertToDateTime(releaseDate);
            await _showtimeRepository.AddAsync(showtime);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Showtime showtime, string releaseDate)
        {
            if (ModelState.IsValid)
            {
                await SaveShowtime(showtime, releaseDate);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Movies = new SelectList(await _movieRepository.GetAllAsync(), "MovieID", "Title", showtime.MovieID);
            ViewBag.Rooms = new SelectList(await _roomRepository.GetAllAsync(), "RoomID", "Name", showtime.RoomID);
            ViewBag.Theaters = new SelectList(await _theaterRepository.GetAllAsync(), "TheaterID", "Name", showtime.TheaterID);
            return View(showtime);
        }


        public DateTime ConvertToDateTime(string releaseDate)
        {
            string format = "yyyy-MM-ddTHH:mm";
            CultureInfo provider = new CultureInfo("vi-VN");
            DateTime dateTime = DateTime.ParseExact(releaseDate, format, provider);
            return dateTime;
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showtime = await _showtimeRepository.GetByIdAsync(id.Value);
            if (showtime == null)
            {
                return NotFound();
            }
            ViewBag.Movies = new SelectList(await _movieRepository.GetAllAsync(), "MovieID", "Title", showtime.MovieID);
            ViewBag.Rooms = new SelectList(await _roomRepository.GetAllAsync(), "RoomID", "Name", showtime.RoomID);
            ViewBag.Theaters = new SelectList(await _theaterRepository.GetAllAsync(), "TheaterID", "Name", showtime.TheaterID);
            return View(showtime);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Showtime showtime, string releaseDate)
        {
            if (id != showtime.ShowtimeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var existingMovie = await _showtimeRepository.GetByIdAsync(id);
                string format = "yyyy-MM-ddTHH:mm";
                CultureInfo provider = new CultureInfo("vi-VN");

                await _showtimeRepository.UpdateAsync(showtime);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Movies = new SelectList(await _movieRepository.GetAllAsync(), "MovieID", "Title", showtime.MovieID);
            ViewBag.Rooms = new SelectList(await _roomRepository.GetAllAsync(), "RoomID", "Name", showtime.RoomID);
            ViewBag.Theaters = new SelectList(await _theaterRepository.GetAllAsync(), "TheaterID", "Name", showtime.TheaterID);
            return View(showtime);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showtime = await _showtimeRepository.GetByIdAsync(id.Value);
            if (showtime == null)
            {
                return NotFound();
            }
            ViewBag.Movies = new SelectList(await _movieRepository.GetAllAsync(), "MovieID", "Title", showtime.MovieID);
            ViewBag.Rooms = new SelectList(await _roomRepository.GetAllAsync(), "RoomID", "Name", showtime.RoomID);
            ViewBag.Theaters = new SelectList(await _theaterRepository.GetAllAsync(), "TheaterID", "Name", showtime.TheaterID);
            return View(showtime);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _showtimeRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WSCinemaNaw/Views/Showtime/Create.cshtml
@model WSCinemaNaw.Models.Showtime

@{
    ViewData["Title"] = "Create Showtime";
}

<h2>Create Showtime</h2>

<form asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="MovieID" class="control-label"></label>
        <select asp-for="MovieID" class="form-control" asp-items="ViewBag.Movies"></select>
        <span asp-validation-for="MovieID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TheaterID" class="control-label"></label>
        <select asp-for="TheaterID" class="form-control" asp-items="ViewBag.Theaters"></select>
        <span asp-validation-for="TheaterID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RoomID" class="control-label"></label>
        <select asp-for="RoomID" class="form-control" asp-items="ViewBag.Rooms"></select>
        <span asp-validation-for="RoomID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShowtimeDate" class="control-label"></label>
        <input asp-for="ShowtimeDate" class="form-control" />
        <span asp-validation-for="ShowtimeDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WSCinemaNaw/Views/Showtime/Delete.cshtml
@model WSCinemaNaw.Models.Showtime

<h2>Delete Showtime</h2>

<h3>Are you sure you want to delete this?</h3>

<form method="post" action="@Url.Action("DeleteConfirmed", "Showtime", new { id = Model.ShowtimeID })">
    <input type="hidden" asp-for="ShowtimeID" />

    <dl class="row">
        <dt class="col-sm-2">ID</dt>
        <dd class="col-sm-10">@Model.ShowtimeID</dd>

        <dt class="col-sm-2">Name Movie</dt>
        <dd class="col-sm-10">@Model.Movie.Title</dd>

        <dt class="col-sm-2">Name Theater</dt>
        <dd class="col-sm-10">@Model.Theater.Name</dd>

        <dt class="col-sm-2">Director</dt>
        <dd class="col-sm-10">@Model.Room.Name</dd>

        <dt class="col-sm-2">Genre</dt>
        <dd class="col-sm-10">@Model.ShowtimeDate.ToShortDateString()</dd>
    </dl>
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index" class="btn btn-primary">Back</a>
</form>

WSCinemaNaw/Views/Showtime/Details.cshtml
@model WSCinemaNaw.Models.Showtime

<h2>Showtime Details</h2>

<dl class="row">
    <dt class="col-sm-2">Showtime ID</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.ShowtimeID)</dd>

    <dt class="col-sm-2">Movie ID</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.Movie.Title)</dd>

    <dt class="col-sm-2">Theater ID</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.Theater.Name)</dd>

    <dt class="col-sm-2">Room ID</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.Room.Name)</dd>

    <dt class="col-sm-2">Showtime Date</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.ShowtimeDate)</dd>
</dl>

WSCinemaNaw/Views/Showtime/Edit.cshtml
@model WSCinemaNaw.Models.Showtime

<h2>Showtime</h2>
<form method="post" action="@Url.Action("Edit", "Showtime", new { id = Model.ShowtimeID })">
    <input type="hidden" asp-for="ShowtimeID" />
    <div class="form-group">
        <label asp-for="MovieID"></label>
        <select asp-for="MovieID" class="form-control" asp-items="ViewBag.Movies"></select>
        <span asp-validation-for="MovieID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TheaterID"></label>
        <select asp-for="TheaterID" class="form-control" asp-items="ViewBag.Theaters"></select>
        <span asp-validation-for="TheaterID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RoomID"></label>
        <select asp-for="RoomID" class="form-control" asp-items="ViewBag.Rooms"></select>
        <span asp-validation-for="RoomID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShowtimeDate"></label>
        <input asp-for="ShowtimeDate" class="form-control" />
        <span asp-validation-for="ShowtimeDate" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
    <a asp-action="Index" asp-route-id="@Model.ShowtimeID" class="btn btn-primary">Back</a>
</form>

WSCinemaNaw/Views/Showtime/Index.cshtml
@model IEnumerable<WSCinemaNaw.Models.Showtime>

<h2>Showtimes</h2>

<table class="table">
    <thead>
        <tr>
            <th>Showtime ID</th>
            <th>Movie ID</th>
            <th>Theater ID</th>
            <th>Room ID</th>
            <th>Showtime Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var showtime in Model)
        {
            <tr>
                <td>@showtime.ShowtimeID</td>
                <td>@showtime.Movie?.Title</td>
                <td>@showtime.Theater?.Name</td>
                <td>@showtime.Room?.Name</td>
                <td>@showtime.ShowtimeDate</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@showtime.ShowtimeID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@showtime.ShowtimeID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@showtime.ShowtimeID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <a asp-action="Create">Thêm danh mục mới</a>
</table>