WSCinemaNaw/Models/Genre.cs
namespace WSCinemaNaw.Models
{
    public class Genre
    {
        public int GenreID { get; set; }
        public string Name { get; set; }
        public List<Movie>? Movies { get; set; }
    }
}

WSCinemaNaw/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using WSCinemaNaw.Models;
using WSCinemaNaw.Repositories.IRepository;

namespace WSCinemaNaw.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreRepository _genreRepository;

        public GenreController(IGenreRepository genreRepository)
        {
            _genreRepository = genreRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _genreRepository.GetAllAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _genreRepository.GetByIdAsync(id.Value);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Genre genre)
        {
            if (ModelState.IsValid)
            {
                await _genreRepository.AddAsync(genre);
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _genreRepository.GetByIdAsync(id.Value);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Genre genre)
        {
            if (id != genre.GenreID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _genreRepository.UpdateAsync(genre);
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _genreRepository.GetByIdAsync(id.Value);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _genreRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WSCinemaNaw/Views/Genre/Create.cshtml
@model WSCinemaNaw.Models.Genre

<h2>Create New Genres</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WSCinemaNaw/Views/Genre/Delete.cshtml
@model WSCinemaNaw.Models.Genre

<h2>Delete Genres</h2>

<h3>Are you sure you want to delete this?</h3>
<form method="post" action="@Url.Action("DeleteConfirmed", "Genre", new { id = Model.GenreID })">
    <input type="hidden" name="Id" value="@Model.GenreID" />
    <div class="form-group">
        <label for="name">Tên danh mục:</label>
        <input type="text" id="name" name="Name" value="@Model.Name" class="form-control" readonly />
    </div>
    <button type="submit" class="btn btn-danger">Xóa</button>
    <a asp-action="Index" asp-route-id="@Model.GenreID" class="btn btn-primary">Back</a>
</form>

WSCinemaNaw/Views/Genre/Edit.cshtml
@model WSCinemaNaw.Models.Genre

<h2>Edit Genres</h2>

<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="GenreID" class="control-label"></label>
        <input asp-for="GenreID" class="form-control" readonly />
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WSCinemaNaw/Views/Genre/Index.cshtml
@model IEnumerable<WSCinemaNaw.Models.Genre>
<h2>Genre</h2>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var genre in Model)
        {
            <tr>
                <td>@genre.GenreID</td>
                <td>@genre.Name</td>
                <td>
                    <a asp-action="Delete" asp-route-id="@genre.GenreID">Delete</a> |
                    <a asp-action="Edit" asp-route-id="@genre.GenreID">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Create">Thêm danh mục mới</a>